### ISSUE TITLE
정류장별 시간표 탭 별도 생성.

### ISSUE THREAD

**Issue by aerain** [jnuro/jedaero#32]
현재는 정류장을 스크롤해야만 원하는 정류장이 나왔음.

정류장 배너를 터치할 시 해당 정류장의 시간표를 보일수 있게 하는 기능 추가할것

**Comment by WonBeomChoi** [comment]
시간표는 정류장별로 1분차이 --> 정문시작으루 알고리즘으로 띄우게 하겠다.

**Comment by aerain** [comment]
#62 fixed
